export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SET_FILTER_SELECT = 'SET_FILTER_SELECT'

export const SET_FILTER_DATE_RANGE = 'SET_FILTER_DATE_RANGE'
